### ISSUE TITLE
wrong message

### ISSUE THREAD

**Issue by dirshell** [xrivendell7/Pwndocker#1]
when i "docker build -t pwndocker ."  i recieve a wrong message：
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ruby2.6
E: Couldn't find any package by glob 'ruby2.6'
E: Couldn't find any package by regex 'ruby2.6'

**Comment by xrivendell7** [comment]
Yeh! Sorry for a long time to respond..
I'll fix it soon.

**Comment by xrivendell7** [comment]
Please try again!
